server:
  port: 8080
##########################################

spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  freemarker:
    cache: false
    expose-spring-macro-helpers: false
    expose-session-attributes: true
    request-context-attribute: request
  profiles:
    active: prod

##########################################

##########################################
logging:
  config: classpath:logback.xml
  level:
    root: error

