
spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  freemarker:
    cache: false
    expose-spring-macro-helpers: false
    expose-session-attributes: true
    request-context-attribute: request
  profiles:
    active: prod
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

##########################################

##########################################
logging:
  config: classpath:logback.xml
#  level:
#    root: error

